name: CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # yarn cache files are stored in `~/.yarn` on Linux/macOS
        path: ~/.yarn 
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - run: npm install yarn

    - name: Verify dependencies
      run: yarn audit

    - name: Install dependencies
      run: yarn

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check code
      run: yarn test

  deploy:
    needs: build

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:

    - uses: actions/checkout@v2

    - name: Deploy Heroku
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name:
      run: gem install dpl

    - name:
      run: dpl --provider=heroku --app=${{ secrets.HEROKU_APP }} --api-key=${{ secrets.HEROKU_API_KEY }}